"""empty message

Revision ID: b502b6a81347
Revises: fca0479dff52
Create Date: 2019-06-15 02:51:06.867148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b502b6a81347'
down_revision = 'fca0479dff52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('absent_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'absent_on')
    # ### end Alembic commands ###
